  volumes:
    mariadb_vol:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/dedsec/Inception-1337/mariadb_volume
    wordpress_vol:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/dedsec/Inception-1337/wordpress_volume
    portainer_data:
      driver: local

  networks:
    network_type:
      driver: bridge
  services:
    nginx:
      build: ./requirements/nginx
      container_name: nginx
      ports:
        - "443:443"
      networks:
        - network_type
      volumes:
        - wordpress_vol:/var/www/html
      restart: on-failure
      depends_on:
        - wordpress
    mariadb:
      build: ./requirements/mariadb
      container_name: mariadb
      ports:
        - "3306:3306"
      env_file:
        - .env
      networks:
        - network_type
      volumes:
        - mariadb_vol:/var/lib/mysql
      restart: on-failure
    wordpress:
      build: ./requirements/wordpress
      container_name: wordpress
      ports:
        - "9000:9000"
      env_file:
        - .env
      networks:
        - network_type
      volumes:
        - wordpress_vol:/var/www/html
      restart: on-failure
      depends_on:
        - mariadb
        - redis
    adminer:
      build: ./requirements/bonus/adminer
      container_name: adminer
      ports:
        - "2000:2000"
      env_file:
        - .env
      networks:
        - network_type
      restart: on-failure
      depends_on:
        - mariadb
    redis:
      build: ./requirements/bonus/redis
      container_name: redis
      ports:
        - "6380:6380"
      env_file:
        - .env
      networks:
        - network_type
      restart: on-failure
    ftp:
      build: ./requirements/bonus/ftp
      container_name: ftp
      ports:
        - "21:21"
        - "21000-21010:21000-21010"  
      networks:
        - network_type
      volumes:
        - wordpress_vol:/uploads
      env_file:
        - .env
      restart: on-failure
      depends_on:
        - wordpress
    portainer:
      build: ./requirements/bonus/portainer
      container_name: portainer
      ports:
        - "9443:9443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      networks:
        - network_type
      restart: on-failure
    website:
      build: ./requirements/bonus/website
      container_name: website
      ports:
        - "8080:80"
      networks:
        - network_type
      restart: on-failure