server {
    listen 443;
    root /var/www/html/;
    index  index.php index.html;
    server_name  kael-ala.42.fr;
    location / {
        try_files $uri $uri/ /index.html?$args;
    }
    # location ~ \.php$ {
    #     fastcgi_pass wordpress:9000;          # Container name:port
    #     fastcgi_index index.php;
    #     include fastcgi_params;                # Basic params (usually exists)
    #     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    #     fastcgi_param PATH_INFO $fastcgi_path_info;
    # }
}